//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PCBoardControls"",
            ""id"": ""61db79d9-5871-4cf7-891d-27a558463c90"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Value"",
                    ""id"": ""4e5fd080-de9e-4a2b-8337-d1299c7aa42c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""be4f1153-a6d7-405d-970b-9003e29a6215"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""402b8112-18b3-4419-b2b5-b59d8b266bfb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""8c78c5b1-89b7-45a4-9027-ad595a4094ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""LeftClick"",
                    ""id"": ""c3919c5b-09a2-4c5c-8976-5328c5606ac4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8c1357d5-1ae4-467b-a9f5-da41a1153f6e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""728b50f2-1655-4ddb-b26e-dfaf108376e4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""528ba3d1-52c3-4ca5-b6eb-bced102f20e4"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""aa3b1e10-8add-4507-8a2c-b734b8636163"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""753e0cee-30db-400b-873f-680092aaa818"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""188eee69-e571-478c-a669-03703850de15"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""9d45bdba-6324-43e8-906a-60568ebf1d21"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""958857a7-4c82-4cc8-bcd5-4d112779a0a0"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""789ecfe3-58f6-482b-bf68-f6da2d04311d"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""RMB + MoveMosue"",
                    ""id"": ""d63f32e2-6a00-45c6-8416-d08cf19d811e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8f0b42cb-b6c8-4536-aa3f-60eaafe4c7ad"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0dd03c60-19cc-4a63-b617-119213cb0faf"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""TouchBoardControls"",
            ""id"": ""6eb8417e-3a8a-4150-88ff-76be19fd82ef"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Value"",
                    ""id"": ""e223f801-fcaf-4369-88b0-fa698d94fc8a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""672a7813-30a4-4510-a106-2fb6bf8ca71c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""3cf4fd3e-c157-406a-b682-9619e087befe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""97f700df-2d1a-4d89-b40c-102073e76128"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3655d4a-a345-4ff8-9211-84cec2860f65"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eaf363c-b3f0-432a-95c8-b00a53326790"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PCBoardControls
        m_PCBoardControls = asset.FindActionMap("PCBoardControls", throwIfNotFound: true);
        m_PCBoardControls_Interact = m_PCBoardControls.FindAction("Interact", throwIfNotFound: true);
        m_PCBoardControls_RotateCamera = m_PCBoardControls.FindAction("RotateCamera", throwIfNotFound: true);
        m_PCBoardControls_Zoom = m_PCBoardControls.FindAction("Zoom", throwIfNotFound: true);
        m_PCBoardControls_Movement = m_PCBoardControls.FindAction("Movement", throwIfNotFound: true);
        // TouchBoardControls
        m_TouchBoardControls = asset.FindActionMap("TouchBoardControls", throwIfNotFound: true);
        m_TouchBoardControls_Interact = m_TouchBoardControls.FindAction("Interact", throwIfNotFound: true);
        m_TouchBoardControls_RotateCamera = m_TouchBoardControls.FindAction("RotateCamera", throwIfNotFound: true);
        m_TouchBoardControls_Zoom = m_TouchBoardControls.FindAction("Zoom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PCBoardControls
    private readonly InputActionMap m_PCBoardControls;
    private IPCBoardControlsActions m_PCBoardControlsActionsCallbackInterface;
    private readonly InputAction m_PCBoardControls_Interact;
    private readonly InputAction m_PCBoardControls_RotateCamera;
    private readonly InputAction m_PCBoardControls_Zoom;
    private readonly InputAction m_PCBoardControls_Movement;
    public struct PCBoardControlsActions
    {
        private @Controls m_Wrapper;
        public PCBoardControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_PCBoardControls_Interact;
        public InputAction @RotateCamera => m_Wrapper.m_PCBoardControls_RotateCamera;
        public InputAction @Zoom => m_Wrapper.m_PCBoardControls_Zoom;
        public InputAction @Movement => m_Wrapper.m_PCBoardControls_Movement;
        public InputActionMap Get() { return m_Wrapper.m_PCBoardControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PCBoardControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPCBoardControlsActions instance)
        {
            if (m_Wrapper.m_PCBoardControlsActionsCallbackInterface != null)
            {
                @Interact.started -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnInteract;
                @RotateCamera.started -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnRotateCamera;
                @Zoom.started -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnZoom;
                @Movement.started -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PCBoardControlsActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_PCBoardControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public PCBoardControlsActions @PCBoardControls => new PCBoardControlsActions(this);

    // TouchBoardControls
    private readonly InputActionMap m_TouchBoardControls;
    private ITouchBoardControlsActions m_TouchBoardControlsActionsCallbackInterface;
    private readonly InputAction m_TouchBoardControls_Interact;
    private readonly InputAction m_TouchBoardControls_RotateCamera;
    private readonly InputAction m_TouchBoardControls_Zoom;
    public struct TouchBoardControlsActions
    {
        private @Controls m_Wrapper;
        public TouchBoardControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_TouchBoardControls_Interact;
        public InputAction @RotateCamera => m_Wrapper.m_TouchBoardControls_RotateCamera;
        public InputAction @Zoom => m_Wrapper.m_TouchBoardControls_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_TouchBoardControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchBoardControlsActions set) { return set.Get(); }
        public void SetCallbacks(ITouchBoardControlsActions instance)
        {
            if (m_Wrapper.m_TouchBoardControlsActionsCallbackInterface != null)
            {
                @Interact.started -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnInteract;
                @RotateCamera.started -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnRotateCamera;
                @Zoom.started -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_TouchBoardControlsActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_TouchBoardControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public TouchBoardControlsActions @TouchBoardControls => new TouchBoardControlsActions(this);
    public interface IPCBoardControlsActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
    }
    public interface ITouchBoardControlsActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
